"""MOP assembly logic.

This module provides functions for assembling Metal-Organic Polyhedra (MOPs)
from Chemical Building Units (CBUs) and Assembly Models (AMs).
"""

from typing import List, Optional, Dict, Any
import os
from datetime import datetime

from twa_mops.core.ontomops import (
    MetalOrganicPolyhedron,
    AssemblyModel,
    ChemicalBuildingUnit,
    Provenance,
    GenericBuildingUnit,
    GBUCoordinateCenter,
    KnowledgeGraph,
)
from twa_mops.core.geo import Vector, Plane
from twa_mops.kg import KnowledgeGraphClient
from twa_mops.config import settings


def assemble_mop(
    am: AssemblyModel,
    cbus: List[ChemicalBuildingUnit],
    provenance: Optional[Provenance] = None,
    kg_client: Optional[KnowledgeGraphClient] = None,
    ccdc: Optional[str] = None,
    upload_geometry: bool = False,
    data_dir: Optional[str] = None,
) -> MetalOrganicPolyhedron:
    """Assemble a MOP from an AM and CBUs.
    
    This function wraps the MetalOrganicPolyhedron.from_assemble class method
    to provide a more convenient interface using KnowledgeGraphClient.
    
    Args:
        am: The AssemblyModel to use for assembly
        cbus: List of ChemicalBuildingUnit instances to assemble
        provenance: Optional provenance information
        kg_client: Optional KnowledgeGraphClient for KG operations
        ccdc: Optional CCDC identifier for the MOP
        upload_geometry: Whether to upload geometry files to KG
        data_dir: Directory for storing geometry files. 
                  If None, uses settings.data_dir or a default subdirectory
    
    Returns:
        A MetalOrganicPolyhedron instance representing the assembled MOP
    
    Raises:
        ValueError: If sparql_client is None and geometry needs to be loaded
    """
    if data_dir is None:
        data_dir = os.path.join(
            os.path.dirname(os.path.abspath(__file__)),
            '..',
            'data',
            f'xyz_mops_{datetime.now().year}_{datetime.now().month}_{datetime.now().day}'
        )
    
    return MetalOrganicPolyhedron.from_assemble(
        am=am,
        lst_cbu=cbus,
        prov=provenance or Provenance(hasReferenceDOI='Generated by MOPTools'),
        ccdc=ccdc,
        sparql_client=kg_client,
        upload_geometry=upload_geometry,
        data_dir=data_dir,
    )


def assemble_mop_from_iris(
    am_iri: str,
    cbu_iris: List[str],
    kg_client: KnowledgeGraphClient,
    provenance: Optional[Provenance] = None,
    depth: int = 1,
    ccdc: Optional[str] = None,
    upload_geometry: bool = False,
    data_dir: Optional[str] = None,
) -> MetalOrganicPolyhedron:
    """Assemble a MOP from IRIs using KnowledgeGraphClient.
    
    This is a convenience function that pulls the AM and CBUs from the KG
    and then assembles the MOP.
    
    Args:
        am_iri: IRI of the AssemblyModel
        cbu_iris: List of IRIs of ChemicalBuildingUnits
        kg_client: KnowledgeGraphClient for KG operations
        provenance: Optional provenance information
        depth: Recursion depth for pulling objects from KG (default: 1)
        ccdc: Optional CCDC identifier for the MOP
        upload_geometry: Whether to upload geometry files to KG
        data_dir: Directory for storing geometry files
    
    Returns:
        A MetalOrganicPolyhedron instance representing the assembled MOP
    """
    # Pull AM and CBUs from KG
    from twa_mops.core.ontomops import AssemblyModel, ChemicalBuildingUnit
    
    am = kg_client.pull_instances(AssemblyModel, [am_iri], depth=depth)[0]
    cbus = kg_client.pull_instances(ChemicalBuildingUnit, cbu_iris, depth=depth)
    
    return assemble_mop(
        am=am,
        cbus=cbus,
        provenance=provenance,
        kg_client=kg_client,
        ccdc=ccdc,
        upload_geometry=upload_geometry,
        data_dir=data_dir,
    )
